#MySQL is mandatory for this plugin
#Login information
host: localhost
port: 3306
username: root
password: password

#Database names (doesn't require adjusting)
database:
  global: uknet_global
  plot: uknet_plots
  navigation: uknet_navigation

#Server configuration
enabled: false
server_name: plotserver

#Save world name
#This is where all completed plots are stored.
save_world: saveWorld

#Limit on active claimed plots
#If user is at the limit they will no longer be able to create a new plot
#Submitted plots are not counted towards the total.
plot_limit:
  guest: 1
  apprentice: 2
  jrbuilder: 3
  builder: 5

#Maximum number of total plots, this includes submitted plots
plot_maximum: 15

#Building points
#Formula is (size+difficulty)*((accuracy+quality)/2)
#The multipliers for accuracy and quality mean that
#for each level from the base of 3 the value shifts by the multiplier.
#Example: at accuracy 1 this would mean 1-(2*accuracy_multiplier)=0.6
size:
  small: 5
  medium: 10
  large: 20
difficulty:
  easy: 3
  normal: 6
  hard: 9
accuracy_multiplier: 0.2
quality_multiplier: 0.2

#Number of days a player can be inactive before their plots get cancelled
plot_inactive_cancel: 14

#Cooldown between plot submissions in minutes
submit_cooldown: 5

#Default area size
#When a player creates a new plot the area of the selection is calculated and will give a default size for the plot.
#The values here represent the largest area in m^2 that will show this size in the plot creation menu.
default_size:
  small: 500
  medium: 1000