#MySQL is manditory for this plugin
#Login information
host: localhost
port: 3306
username: root
password: password

#Database names (doesn't require adjusting)
database:
    global: uknet_global
    plot: uknet_plots
    navigation: uknet_navigation
    
#Server configuration
enabled: false
server_name: plotserver

#Limit on active claimed plots
#If user is at the limit they will no longer be able to create a new plot
plot_limit:
    guest: 1
    apprentice: 2
    jrbuilder: 3
    builder: 5

#Maximum number of total plots, this includes submitted plots
plot_maximum: 15

#Building points
#Points multiplier for each level
#Example if size is 3 and size_multiplier is 5 then the player will receive 3*5=15 points for size.
#This is done for each of the three categories
size_multiplier: 1
accuracy_multiplier: 1
quality_multiplier: 1
points_base: 5

#Number of days a player can be inactive before their plots get cancelled
plot_inactive_cancel: 14

#Cooldown between plot submissions in minutes
submit_cooldown: 5