name: PlotSystem
version: '${project.version}'
main: net.bteuk.plotsystem.PlotSystem
api-version: '1.21.1'

dependencies:
  server:
    WorldGuard:
      load: BEFORE
      required: true
      join-classpath: true
    WorldEdit:
      load: BEFORE
      required: true
      join-classpath: true
    LuckPerms:
      load: BEFORE
      required: true
      join-classpath: true
    Multiverse-Core:
      load: BEFORE
      required: true
      join-classpath: true
    Network:
      load: BEFORE
      required: true
      join-classpath: true
    VoidGen:
      load: BEFORE
      required: true
      join-classpath: true