name: PlotSystem
version: 1.0.0
main: me.elgamer.plotsystem.Main
description: Plot System for UKnet
depend: [ WorldGuard, WorldEdit, LuckPerms, HolographicDisplays, Multiverse-Core ]
api-version: 1.17

commands:
  plotsystem:
    aliases: [ps]
    usage: /<command>
    description: Deals will all plotsystem related commands.
  claim:
    usage: /<command>
    description: Used to claim the plot you're standing in.