name: PlotSystem
version: '${project.version}'
main: me.bteuk.plotsystem.PlotSystem
description: Plot System for UKnet
depend: [ WorldGuard, WorldEdit, LuckPerms, Multiverse-Core , Network , VoidGen ]
api-version: 1.18

commands:
  plotsystem:
    aliases: [ps]
    usage: /<command>
    description: Deals will all plotsystem related commands.
  claim:
    aliases: [claim]
    usage: /<command>
    description: Used to claim the plot you're standing in.